apiVersion: apps/v1
kind: Deployment
metadata:
  name: template-frontend-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: template-frontend-deployment
  template:
    metadata:
      labels:
        app: template-frontend-deployment
    spec:
      containers:
        - name: template-frontend
          image: elghibaomar/template-frontend:latest
          env:
            - name: PORT
              value: "8081"
          ports:
          - containerPort: 8081


---
apiVersion: v1
kind: Service
metadata:
  name: template-frontend-service
spec:
  type: LoadBalancer
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8081
  selector:
    app: template-frontend-deployment






